// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAzk-b7Bdf6knZtnMetI2-c3BxbjWwbZk',
    appId: '1:847988643992:web:9dcc5030888318b83a58ed',
    messagingSenderId: '847988643992',
    projectId: 'ecoquest-9b88b',
    authDomain: 'ecoquest-9b88b.firebaseapp.com',
    storageBucket: 'ecoquest-9b88b.firebasestorage.app',
    measurementId: 'G-NDRWL47EPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmG0Iil4NvQdfV36jUZ6Fu_ByBA6S4dY',
    appId: '1:847988643992:android:af6cad9fa111afe63a58ed',
    messagingSenderId: '847988643992',
    projectId: 'ecoquest-9b88b',
    storageBucket: 'ecoquest-9b88b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8nkwYJ00LEM9v8v27eixmRXObB_0gxwo',
    appId: '1:847988643992:ios:7966875a5c10d4d53a58ed',
    messagingSenderId: '847988643992',
    projectId: 'ecoquest-9b88b',
    storageBucket: 'ecoquest-9b88b.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8nkwYJ00LEM9v8v27eixmRXObB_0gxwo',
    appId: '1:847988643992:ios:7966875a5c10d4d53a58ed',
    messagingSenderId: '847988643992',
    projectId: 'ecoquest-9b88b',
    storageBucket: 'ecoquest-9b88b.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAzk-b7Bdf6knZtnMetI2-c3BxbjWwbZk',
    appId: '1:847988643992:web:1d36a83b0706726d3a58ed',
    messagingSenderId: '847988643992',
    projectId: 'ecoquest-9b88b',
    authDomain: 'ecoquest-9b88b.firebaseapp.com',
    storageBucket: 'ecoquest-9b88b.firebasestorage.app',
    measurementId: 'G-B91RE6VQ8B',
  );
}
